---
- hosts: localhost
  connection: local
  vars_files:
     - ../../../ec2_credentails.yml
  
  tasks:
  - name: instance creation
    amazon.aws.ec2_instance:
       name: "{{ item.name }}"
       region: us-east-1
       key_name: EC2Keys
       image_id: "{{ item.image }}"
       vpc_subnet_id: subnet-0e0f5dfc40da07e78
       security_group: default
       aws_access_key: "{{ ec2_access_key }}"
       aws_secret_key: "{{ ec2_secret_key }}"
       instance_type: t2.micro
       network:
         assign_public_ip: yes
    loop: 
      - { image: "ami-05b10e08d247fb927", name: "RedHat1" } # Update AMI ID according 
      - { image: "ami-05b10e08d247fb927", name: "Redhat2" } # to your account
      - { image: "ami-04b4f1a9cf54c11d0", name: "Ubuntu" }