---
- hosts: all
  become: true

  tasks:
    #- name: print all ansible facts
     # ansible.builtin.debug: 
      #  var: ansible_facts

    - name: shutdown ubuntu instance
      ansible.builtin.command: shutdown -h now
      when:
        ansible_facts['os_family'] == "Debian"
        