---
- hosts: localhost
  connection: local
  vars_files:
    - ../../../pass.yml # pass the exact location of the ec2 keys location
  
  tasks:
  - name: Start EC2 instance
    amazon.aws.ec2_instance:
      aws_access_key: "{{ ec2_access_key }}" # this will fetch from above vars_files passed location
      aws_secret_key: "{{ ec2_secret_key }}" # this will fetch from above vars_files passed location
      region: us-east-1
      name: Ansible-EC2-Instance
      instance_type: t2.micro
      vpc_subnet_id: subnet-0e0f5dfc40da07e78
      image_id: ami-05b10e08d247fb927
      key_name: EC2Keys
      security_groups: ["default"]
      network:
        assign_public_ip: true
      count: 1


